//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCT.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Id { get; set; }
        public string CurrencyCode { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> FxRate { get; set; }
        public Nullable<decimal> RPI { get; set; }
        public int CountryId { get; set; }
        public string RenewalYear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
