//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCT.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCTEntities : DbContext
    {
        public GCTEntities()
            : base("name=GCTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BudgetVarianceReason> BudgetVarianceReasons { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<PrimaryVariance> PrimaryVariances { get; set; }
        public virtual DbSet<SecondaryVariance> SecondaryVariances { get; set; }
        public virtual DbSet<Tracker> Trackers { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
