//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCT.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker
    {
        public int Id { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string Region { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string ResponsibilityCentreNumber { get; set; }
        public string ResponsibilityCentreName { get; set; }
        public string ExpenseCategory { get; set; }
        public int VendorId { get; set; }
        public string RequisitionNumber { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> LocalCcyFxRate { get; set; }
        public Nullable<decimal> LocalCcyRPIRate { get; set; }
        public string BudgetLocalCcy { get; set; }
        public string BudgetUSCcy { get; set; }
        public string ActualLocalCcy { get; set; }
        public string ActualUSCcy { get; set; }
        public Nullable<System.DateTime> CashStartDate { get; set; }
        public Nullable<System.DateTime> CashEndDate { get; set; }
        public Nullable<System.DateTime> PLStartDate { get; set; }
        public Nullable<System.DateTime> PLEndDate { get; set; }
        public string RequisitionDescription { get; set; }
        public Nullable<int> PrimaryVarianceId { get; set; }
        public Nullable<int> SecondaryVarianceId { get; set; }
        public string ReceiptNumber { get; set; }
        public string Comments { get; set; }
        public string Renewal { get; set; }
        public Nullable<decimal> TotalBudget { get; set; }
        public Nullable<decimal> VarianceInBudget { get; set; }
        public Nullable<decimal> NextYrLocalCcyBudget { get; set; }
        public Nullable<decimal> NextYrUSCcyBudget { get; set; }
        public string InternalContractor { get; set; }
        public string ITDirector { get; set; }
        public string AdditionalComments { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual PrimaryVariance PrimaryVariance { get; set; }
        public virtual SecondaryVariance SecondaryVariance { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
